title: aj
tagline: The personal blog of a hacker
permalink: pretty
exclude: [Gemfile, Gemfile.lock, README.md, vendor]
markdown:
  kramdown:
    input: GFM
baseurl: /
editor: emacs .
disqus_sitename: ajwrites
